name: Documentation
on:
  workflow_dispatch: {}
  push:
    branches:
      - master
    paths:
      - "docs/**"
      - ".vitepress/**"
      - "**/test-folder/**"
jobs:
  # deploy_docs:
  # runs-on: ubuntu-latest
  # permissions:
  #   pages: write
  #   id-token: write
  # environment:
  #   name: github-pages
  #   url: ${{ steps.deployment.outputs.page_url }}
  # steps:
  #   - uses: actions/checkout@v3
  #     with:
  #       fetch-depth: 0
  #   - uses: actions/setup-node@v3
  #     with:
  #       node-version: 19
  #   - name: Install pnpm
  #     uses: pnpm/action-setup@v2
  #     id: pnpm-install
  #     with:
  #       version: 8
  #       run_install: false
  #   - run: pnpm install --frozen-lockfile --ignore-scripts --prefer-offline
  #   - name: Build
  #     run: npm run docs:build
  #   - uses: actions/configure-pages@v2
  #   - uses: actions/upload-pages-artifact@v1
  #     with:
  #       path: docs/.vitepress/dist
  #   - name: Deploy
  #     id: deployment
  #     uses: actions/deploy-pages@v1
  #   - name: Summary
  #     run: echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY
  echo_console:
    runs-on: ubuntu-latest
    steps:
      - name: Echo to console
        run: echo "Hello world"
